server:
  port: 8002 #指定运行端口
logging:
  level:
    root: INFO
  file:
    name: logs/${spring.cloud.client.ip-address}/${spring.application.name}.log
    path: logs
spring:
  application:
    name: eureka-server #指定服务名称
  security:
    user:
      name: admin
      password: YIpotfg8Z8TKA29ox
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}  #指定主机地址
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
  server:
    enable-self-preservation: false  #保护模式是否开启
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always